### ISSUE TITLE
Where is the UD_to_SUD.grs  file?

### ISSUE THREAD

**Issue by Aditi138** [surfacesyntacticud/tools#3]
Same as title.

**Comment by perrier54** [comment]
You can download the UD+_to_SUD.grs file at URL [https://github.com/surfacesyntacticud/tools/tree/master/converter/grs](url)

**Comment by bguil** [comment]
The `README` file of the [converter](https://github.com/surfacesyntacticud/tools/blob/master/converter/README.md) was outdated, sorry for this. I've just fix it.

The file `UD_to_SUD.grs` has been renamed to `UD+_to_SUD.grs`. Note that this file uses another file in the same directory, so a `git clone` is probably the easier option.
